24 ma mammals.js
jasminedns/australia-zoo pull request #17
Opened 2024-11-25 17:54 UTC by Moon2024-light

please review my mammals.js file thanks

2024-11-26 10:37 UTC, potnurusrilatha approved these changes
please give a folder name correctly

2024-11-26 12:12 UTC, TobiasKjernell requested changes

2024-11-26 12:12 UTC, TobiasKjernell commented on scripts/mammls.js
miss spelled. correct: "mammels"

2024-11-26 13:31 UTC, TobiasKjernell approved these changes

2024-11-27 11:09 UTC, jasminedns commented
old branch

2024-11-27 11:09 UTC, closed without merging