27 tk group js and objects
jasminedns/australia-zoo pull request #34
Opened 2024-11-27 14:38 UTC by TobiasKjernell

Added object function for team members. Added pictures and information for each person for further tasks.

2024-11-27 16:24 UTC, jasminedns requested changes

2024-11-27 16:24 UTC, jasminedns commented on images/team/srilatha.jpg
The image is too small compared to the others

2024-11-27 16:24 UTC, jasminedns commented on scripts/aboutus.js
> +    jasminD = new TeamMember("Jasmine Danese", ["Gaming", "Procrastinate"], "Italy", ["Otter", "Quokka", "Capybara", "Raccoon", "Fox"], "../images/team/jasmine.jpg");
misspelled jasmine in L2 and L19

2024-11-27 16:24 UTC, jasminedns commented on scripts/aboutus.js
> +    carolineL = new TeamMember("Caroline Lindbom", ["Hiking"], "Sweden", ["Dog", "Alpacka", "Raven", "Owl", "Cat"], "../images/team/caroline.jpg");
misspelled alpaca

2024-11-27 18:21 UTC, potnurusrilatha approved these changes
looks ok

2024-11-27 22:22 UTC, Moon2024-light approved these changes
looks good!

2024-11-28 13:57 UTC, idacarlin95 approved these changes
looks good to me

2024-11-28 14:12 UTC, jasminedns approved these changes
Good to go!

2024-11-29 14:24 UTC, merged