coding added for  hamburger menu and icon in   css and js fils
jasminedns/australia-zoo pull request #37
Opened 2024-11-27 22:09 UTC by Moon2024-light

hi,team "coding added for  hamburger menu and icon in html,  css and js fils" please review thanks

2024-11-28 11:23 UTC, jasminedns requested changes
I've commented on some lines where you can edit or add some things. Also remember to use variables so that if we want to change colors or sizes we can do it only in variables and the changes will be applied to every document

2024-11-28 11:23 UTC, jasminedns commented on index.html
> +    <link rel="stylesheet" href="./styles/index.css">
instead of doing the css in main copy paste it in general cause we're gonna use it for every page

2024-11-28 11:23 UTC, jasminedns commented on index.html
> +        <ul>
You can put the html links in

2024-11-28 11:23 UTC, jasminedns commented on index.html
> +            <li><a href="#">HOME PAGE</a></li>
I'd name this one HOME instead of HOME PAGE

2024-11-28 11:23 UTC, jasminedns commented on styles/index.css
> +    font-family: 'Arial', sans-serif;
we're gonna use koho for this so link the css koho file in the head and change "arial" to "Ko-Ho"

2024-11-28 11:23 UTC, jasminedns commented on styles/index.css
> +    background-color: #F5F0D7; /* Beige background */
you can use the variable here

2024-11-28 12:42 UTC, Moon2024-light reviewed
i made changes please review thanks

2024-11-28 14:17 UTC, jasminedns requested changes
make sure every color and size is using a variable too

2024-11-28 14:17 UTC, jasminedns commented on index.html
> +    <link rel="stylesheet" href="./styles/general.css">
delete this line since general it's already been linked in L7

2024-11-28 14:17 UTC, jasminedns commented on index.html
> +            <li><a href="#home">HOME</a></li>
#home is not a link. You need to put the path to the html page

2024-11-28 14:17 UTC, jasminedns commented on styles/general.css
> +    --title-tertiary: #F5F0D7;
wrong way to use variable

2024-11-28 14:41 UTC, TobiasKjernell commented on styles/general.css
> +    --title-tertiary: #F5F0D7;
var(--title-tertiary);

2024-11-28 18:41 UTC, jasminedns requested changes

2024-11-28 18:41 UTC, jasminedns commented on index.html
> +    <script src="./scripts/index.js"></script>
also this link has to be in the head and you need to add defer after the source

2024-11-28 20:56 UTC, Moon2024-light commented
i made changes please review thanks

2024-11-29 09:40 UTC, TobiasKjernell requested changes

2024-11-29 09:40 UTC, TobiasKjernell commented on styles/general.css
> +    top: var(--border-radius);
don't see why we use the radius variable for something like this. Should have their own if needed.

2024-11-29 09:40 UTC, TobiasKjernell commented on styles/general.css
> +    transition: background-color var(--transition-speed) ease;
this variable doesn't exist, need to make this one

2024-11-29 09:40 UTC, TobiasKjernell commented on styles/general.css
> +    box-shadow: -2px 0 5px var(--shadow-heavy);
same here, this variable doesnt exist, make one

2024-11-29 13:18 UTC, jasminedns requested changes

2024-11-29 13:18 UTC, jasminedns commented on index.html
> +            <li><a href="about.html">ABOUT US</a></li>
the index link is right but the rest need to go inside the html folder first ex. for birds would be: href="html/birds.html"

2024-11-29 13:18 UTC, jasminedns commented on styles/general.css
> +    box-shadow: 0px 4px 6px var(--shadow-light); /* Using light shadow */
the variable does not exist at the moment, so it won't know what you mean. You can just type in the value you want to or create a new variable in variables.css with the same name and give it a value

2024-11-29 13:18 UTC, jasminedns commented on styles/general.css
> +    top: var(--border-radius);
use the border radius variable for border radius only

2024-11-29 13:28 UTC, jasminedns requested changes
added some new comment reviews

2024-11-29 22:15 UTC, Moon2024-light reviewed
please review my changes thanks

2024-11-30 00:23 UTC, potnurusrilatha submitted a review, later dismissed

2024-11-30 00:23 UTC, potnurusrilatha commented on styles/general.css
> +    background-color: #F5F0D7; /* Beige background */
i think color should be from variable css

2024-11-30 00:23 UTC, potnurusrilatha commented on styles/general.css
> +    background-color: #F5F0D7; /* Beige background */
i think background color should be from texture

2024-11-30 09:53 UTC, Moon2024-light reviewed
please check i added variables coding thanks

2024-11-30 09:55 UTC, Moon2024-light reviewed
please review again thanks

2024-11-30 12:14 UTC, jasminedns requested changes
you could delete reptiles.html and reptiles.js from this branch so we can have the menu ready after the changes. So delete it from this branch and create another one for js so there's less confusion

2024-11-30 12:14 UTC, jasminedns commented on html/reptiles.html
> +    <title>Linking JavaScript Example</title>
the title should be reptiles

2024-11-30 12:14 UTC, jasminedns commented on styles/general.css
> +    background-color: #3C5724; /* Default green */
add the variable here

2024-11-30 12:14 UTC, jasminedns commented on styles/general.css
> +    background-color: #F07300; /* Orange on hover */
add variable here

2024-11-30 12:14 UTC, jasminedns commented on styles/general.css
> +    color: #3C5724;
add variable

2024-11-30 12:14 UTC, jasminedns commented on styles/general.css
> +    color: #89AA4F; /* Light green on hover */
add variable

2024-11-30 12:14 UTC, jasminedns commented on scripts/reptiles.js
> +        alert("Button was clicked!");
we need the reptiles to appear in the page when clicked, not an alert

2024-11-30 12:14 UTC, jasminedns commented on html/reptiles.html
> +    <button id="myButton">Click Me!</button>
You'd probably need 3 since we have 3 reptiles

2024-11-30 12:52 UTC, Moon2024-light reviewed
please check changes

2024-11-30 12:56 UTC, jasminedns approved these changes
we have it! good to go imo

2024-11-30 13:18 UTC, jasminedns approved these changes

2024-11-30 18:02 UTC, TobiasKjernell approved these changes

2024-12-02 12:58 UTC, merged