37 cl index js events
jasminedns/australia-zoo pull request #51
Opened 2024-12-04 13:30 UTC by idacarlin95

2024-12-04 14:28 UTC, TobiasKjernell commented on scripts/index.js
> +    const welcomeMessage = document.getElementById("welcome-message");
här kan du avsluta med _el eller El på variablen så nästa person som kommer in här vet att det är en Element variable istället att man tror det är en string med message. Så du kan byta dom variablerna dom har en element som referrens

2024-12-04 14:32 UTC, TobiasKjernell commented on scripts/index.js
> +    const welcomeMessage = document.getElementById("welcome-message");
Dessa variabler kan vi ha utanför funktionen också, så vi inte behöver "leta" efter dom varje knapp tryck

2024-12-04 14:49 UTC, TobiasKjernell commented on scripts/index.js
> +        welcomeMessage.textContent = welcomeMessage.dataset.default;
clenup html and use a stored variables / team meeting

2024-12-04 14:49 UTC, TobiasKjernell commented on scripts/index.js
> +        animalImage.style.display = 'none';
use general hidden class css / team meeting

2024-12-04 14:50 UTC, TobiasKjernell commented on scripts/index.js
> +        animalImage.style.display = 'block';
make a block class in css and reuse it. add class / team meeting

2024-12-04 14:50 UTC, TobiasKjernell commented on scripts/index.js
> +        const li = document.createElement("li");
rename variable to button_li so we knows it's a "button" we reading about

2024-12-04 15:48 UTC, jasminedns requested changes
Make the changes and we're good to go!

2024-12-04 15:48 UTC, jasminedns commented on index.html
> +            <h1 id="welcome-message" data-default="WELCOME TO THE ZOO KEEPERS OFFICIAL PAGE!">WELCOME TO THE "ZOO KEEPERS" OFFICIAL PAGE!</h1>
Just saw this.. We can't use h1 for both the logo group name and this one. Please change it to something else and restyle it

2024-12-05 16:08 UTC, TobiasKjernell approved these changes

2024-12-05 19:08 UTC, jasminedns approved these changes

2024-12-06 09:13 UTC, Moon2024-light approved these changes
looks good!

2024-12-06 09:56 UTC, merged