added coding for reptils js
jasminedns/australia-zoo pull request #54
Opened 2024-12-05 09:20 UTC by Moon2024-light

please review my reptiles onclick event file thanks

2024-12-05 09:21 UTC, TobiasKjernell commented on html/reptiles.html
> +    <script src="../scripts/reptiles.js"defer></script>
make a space here between "defer" and script name, just for some beeuty

2024-12-05 11:37 UTC, idacarlin95 approved these changes
think it looks good

2024-12-05 14:38 UTC, Moon2024-light reviewed
fixed js link

2024-12-05 14:39 UTC, TobiasKjernell approved these changes

2024-12-06 09:15 UTC, TobiasKjernell requested changes
need to add length/weight, found at etc. some informations is missing

2024-12-06 10:05 UTC, Moon2024-light reviewed
added coding please check thanks

2024-12-06 10:36 UTC, jasminedns approved these changes
looks ok!

2024-12-06 11:41 UTC, TobiasKjernell approved these changes

2024-12-06 15:31 UTC, merged